### ISSUE TITLE
Intake temp and pressure ( map sensor parameters)

### ISSUE THREAD

**Issue by hooman8219** [0xCAFEDECAF/VanLiveConnect#1]
Hi can you add map sensor parameters like manifold temp? Or them are on kline?🥲

**Comment by 0xCAFEDECAF** [comment]
Hi, these parameters are not by default sent on the VAN bus. Maybe there is diagnostic data, but those packets are not by default present on the bus. It would be nice to be able to trigger this kind of packets, however for that it would probably be necessary to transmit the diagnostic request packets. The current version of VanLiveConnect does not support the sending (back) of packets onto the VAN bus.

**Comment by hooman8219** [comment]
Peugeot use kline for connecting esp(abs unit)-ecu-bm34(bsm) . That's available in obd2 port 😅 lam trying to connect Arduino or sth else to "realdash"apk

**Comment by 0xCAFEDECAF** [comment]
I understand, however the VAN bus is not the same as the OBD2 port.
