### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Diskdruid** [0xCAFEDECAF/VanLiveConnect#6]
'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)' is protected within this context

Probably missing a step somewhere but this is my 8th time running through all the steps checking each one along the way and still get stopped at the message and help would be appreaciated

**Comment by 0xCAFEDECAF** [comment]
Strange. Are you using the latest version of [arduinoWebSockets](https://github.com/Links2004/arduinoWebSockets)?

The function:

`bool clientIsConnected(uint8_t num);`

(as used [here](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/b831a73949e0695974db9d4ee6e980efa1aa7660/VanLiveConnect/WebSocket.ino#L102) and [here](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/b831a73949e0695974db9d4ee6e980efa1aa7660/VanLiveConnect/WebSocket.ino#L133))

was added here:

https://github.com/Links2004/arduinoWebSockets/commit/4acc7eff8a283be62fb548ef9e07872162eff7cf#diff-88a9b9d6192520c59ba2288d5496760a93b0ac4c2537c2c55852385b8544a210

**Comment by Diskdruid** [comment]
I was using the latest version then moved back to 2.2 as was the one listed. full error dump : -

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 160 MHz, Flash, Disabled (new aborts on oom), Disabled, Basic SSL ciphers (lower ROM use), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:1MB OTA:~1019KB), v2 Lower Memory (no features), Disabled, None, Only Sketch, 921600"

C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino: In function 'void SendSavedJson()':

WebSocket:102:57: error: 'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)' is protected within this context

  102 |             if (webSocket.clientIsConnected(websocketNum) && webSocket.sendTXT(websocketNum, savedJson[i]))

      |                                                         ^

In file included from C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino:3:

C:\Users\DaveM\Documents\Arduino\libraries\arduinoWebSockets-2.2.0\src/WebSocketsServer.h:128:10: note: declared protected here

  128 |     bool clientIsConnected(WSclient_t * client);

      |          ^~~~~~~~~~~~~~~~~

WebSocket:102:45: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'WSclient_t*' [-fpermissive]

  102 |             if (webSocket.clientIsConnected(websocketNum) && webSocket.sendTXT(websocketNum, savedJson[i]))

      |                                             ^~~~~~~~~~~~

      |                                             |

      |                                             uint8_t {aka unsigned char}

In file included from C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino:3:

C:\Users\DaveM\Documents\Arduino\libraries\arduinoWebSockets-2.2.0\src/WebSocketsServer.h:128:41: note:   initializing argument 1 of 'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)'

  128 |     bool clientIsConnected(WSclient_t * client);

      |                            ~~~~~~~~~~~~~^~~~~~

C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino: In function 'void SendJsonOnWebSocket(const char*, bool)':

WebSocket:133:92: error: 'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)' is protected within this context

  133 |     if (websocketNum == WEBSOCKET_INVALID_NUM || ! webSocket.clientIsConnected(websocketNum))

      |                                                                                            ^

In file included from C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino:3:

C:\Users\DaveM\Documents\Arduino\libraries\arduinoWebSockets-2.2.0\src/WebSocketsServer.h:128:10: note: declared protected here

  128 |     bool clientIsConnected(WSclient_t * client);

      |          ^~~~~~~~~~~~~~~~~

WebSocket:133:80: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'WSclient_t*' [-fpermissive]

  133 |     if (websocketNum == WEBSOCKET_INVALID_NUM || ! webSocket.clientIsConnected(websocketNum))

      |                                                                                ^~~~~~~~~~~~

      |                                                                                |

      |                                                                                uint8_t {aka unsigned char}

In file included from C:\Users\DaveM\Desktop\VanLiveConnect-main\VanLiveConnect\WebSocket.ino:3:

C:\Users\DaveM\Documents\Arduino\libraries\arduinoWebSockets-2.2.0\src/WebSocketsServer.h:128:41: note:   initializing argument 1 of 'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)'

  128 |     bool clientIsConnected(WSclient_t * client);

      |                            ~~~~~~~~~~~~~^~~~~~

exit status 1

'virtual bool WebSocketsServer::clientIsConnected(WSclient_t*)' is protected within this context



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


any ideas on how to fix it would be much appreactiated am looking forward to getting this working

**Comment by Diskdruid** [comment]
sorted it thank you for your help can see where I went wrong now

**Comment by 0xCAFEDECAF** [comment]
I just [updated](https://github.com/0xCAFEDECAF/VanLiveConnect/commit/c0235bfe76a5079df722c10132ceb99940f94aa0) the README.md file.

Thanks for reporting this issue!

**Comment by 0xCAFEDECAF** [comment]
[Updated](https://github.com/0xCAFEDECAF/VanLiveConnect/commit/c0235bfe76a5079df722c10132ceb99940f94aa0) the README.md file.
