### ISSUE TITLE
IR receiver - I don't see any signals

### ISSUE THREAD

**Issue by maltsevvv** [0xCAFEDECAF/VanLiveConnect#9]
Hello. I use NodeMCU v3. Arduino IDE 2.3.2
I don’t see the port in the monitor, IR signals from the remote control (Samsung, LG)
TSOP 4838
Not connected to the machine (if this is important)
On the NodeMCU they are connected as in the diagrams (D5,D6,D7)
In Config.h I uncommented the line
`#define DEBUG_IR_RECV`
uploaded a sketch

VanBus version 0.4.0 initialized; VanBusRx queue of size 30 is set up
Setting up IR receiver
ESP will enter light sleep mode after 5:00 minutes of inactivity; listening on pin D1 (GPIO5) for VAN bus activity to wake up from sleep.
Connected to Wi-Fi SSID '*******'
Wi-Fi signal strength (RSSI): -52 dB
Please surf to: http://192.168.1.122/MFD.html

Maybe there is still something that needs to be done?

**Comment by 0xCAFEDECAF** [comment]
Hi, the IR functions only work with the [original remote control](https://github.com/0xCAFEDECAF/Peugeot406MfdTypecIrSendArduino/raw/master/Peugeot%20406%20MFD%20type%20C%20remote%20control.jpg) (that comes with the vehicle), and the [MFD type C](https://github.com/0xCAFEDECAF/Peugeot406MfdTypecIrSendArduino/raw/master/Peugeot%20406%20MFD%20type%20C.png). The VAN bus pins [must be connected](https://github.com/0xCAFEDECAF/VanLiveConnect?tab=readme-ov-file#schematics) to the vehicle's VAN bus.

**Comment by maltsevvv** [comment]
Thank you. Now I understand. I just have a 5" display on my Peugeot 607.
Sorry for the stupid question
